### ISSUE TITLE
Question regarding compilation of libtensorflow_inference.so for armeabi

### ISSUE THREAD

**Issue by polaroidkidd** [BrowningWan/fast-neural-style-android-app#1]
Hi

I saw your project and noticed you had compiled libtensorflow_inference.so for armeabi (not armeabi-v7a) and was wondering how you achieved this? I tried using your compiled version in my app but it couldn't load my custom model with the error message below, but I'm not sure where to start. Any pointers would be appreciated. 

```
    Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef 
mentions attr 'index_type' not in Op<name=Fill; signature=value:T -> 
output:T; attr=T:type>; NodeDef: MultipleGridAnchorGenerator/Meshgrid_17/ExpandedShape_1/ones
 = Fill[T=DT_INT32, index_type=DT_INT32]
(MultipleGridAnchorGenerator/Meshgrid_17/ExpandedShape_1/Reshape, MultipleGridAnchorGenerator/Meshgrid_17/ExpandedShape_1/ones/Const). 

(Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```

**Comment by BrowningWan** [comment]
Sorry to reply so late because of my dissertation defense just finished yesterday. The file libtensorflow_inference.so used in this android project here is downloaded in this page: [here](https://ci.tensorflow.org/view/Nightly/nightly-android/,) you can download different .so files used for the other cpu (like armeabi-v7a), but, hmmm, I don't know why the nightly-android was 404. The url [here](http://ci.tensorflow.org/view/Nightly) contains the other compiled tensorflow file and demo, so maybe the newest file used in Android can be found after few days. If you want to compile for yourself, just follow this [page](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/android/README.md) Bazel is recommended to use for compiling. What you need to do is just change the cpu you want to use:

```
bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so \
   --crosstool_top=//external:android/crosstool \
   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
   --cpu=armeabi-v7a
```

Hope the answer here can solve your problem.  ( =•ω•= )

**Comment by polaroidkidd** [comment]
Hi, thanks for getting back. Hope your defense went well! Mine is coming up (BSc) soon as well so I understand the pressure involved.

I've since managed to compile it using bazel (using pretty much the above command) and have managed to resolve all of the compilation problems. The URL is still down in TF (even coming directly from the [readMe](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) they provide. 

Enjoy your post-defense time!
